version: '3.7'

services: 
  flask:
    build: ./services/flask
    # command: [sh, -c, "python manage.py reset_db && python manage.py seed_all && flask run --host=0.0.0.0"]
    command: [sh, -c, "flask run --host=0.0.0.0"]
    volumes: 
      - ./services/flask:/usr/src/  # bind mounting folder for development
    ports: 
      - 8080:5001 # export container 5001 port to localhost:8080
    env_file:
     - ./.env.dev
    depends_on: 
      - psqldb

  psqldb:
    # build: ./services/db
    image: postgres:12.0-alpine
    ports: 
      - 5432:5432
    volumes: 
      - postgres_data:/var/lib/postgresql/data # persistent volume for development
    env_file:
      - ./.env.dev
volumes:
  postgres_data: